name: Run autotests


on: 
  workflow_dispatch:
   inputs:
      diployment target:
        description: select test to run
        required: true
        type: choice
        default: all
        options:
          - all



jobs:
   run-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
     - name: Copy source code
       uses: actions/checkout@v4
       
     - name: Set up Python env
       uses: actions/setup-python@v5  
       with:
         python-version: "3.10"

     - name: Upgrade pip, setuptools, and wheel
       run: python -m pip install --upgrade pip setuptools wheel

     - name: Fix system version parsing issue
       run: |
         export SYSTEM_VERSION=$(uname -r | cut -d'-' -f1)
         echo "Fixed system version: $SYSTEM_VERSION"

     - name: Force install packaging module
       run: |
         pip install --force-reinstall --no-cache-dir --ignore-installed "packaging<24.0"

     - name: Install dependencies
       run: pip install --no-cache-dir --disable-pip-version-check -r requirements.txt

     - name: Run tests
       run: pytest -v

    
     
      
    
   
