name: Run autotests


on: 
  workflow_dispatch:
   inputs:
      diployment target:
        description: select test to run
        required: true
        type: choice
        default: all
        options:
          - all


jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
     - name: Copy source code
       uses: actions/checkout@v4
       
     - name: Set up Python env
       uses: actions/setup-python@v5  
       with:
         python-version: "3.12"

     - name: Upgrade pip, setuptools, and wheel
       run: python -m pip install --upgrade pip setuptools wheel

     - name: Patch pip to fix invalid version issue
       run: |
         sed -i 's/self.version = Version(version)/self.version = Version(version.split("-")[0])/' \
         $(python -c "import pip; print(pip.__file__)")/../_vendor/packaging/version.py
  

     - name: Force install packaging module
       run: |
         pip install --force-reinstall --no-cache-dir --ignore-installed "packaging<24.0"

     - name: Debug environment
       run: |
         echo "Kernel version: $(uname -r)"
         python -c "import platform; print('Platform:', platform.platform())"
         python -c "import sys; print('Python version:', sys.version)"
         python -c "import packaging.version; print(packaging.version.Version('6.8.0'))"


     - name: Install dependencies
       run: pip install -r requirements.txt

     - name: Run tests
       run: pytest -v

    
     
      
    
   
